module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['IBM Plex Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        'luxury-crm': {
          primary: '#0A192F',
          'primary-content': '#FFFFFF',
          secondary: '#64748B',
          'secondary-content': '#FFFFFF',
          accent: '#D4AF37',
          'accent-content': '#0A192F',
          neutral: '#0A192F',
          'neutral-content': '#FFFFFF',
          'base-100': '#FFFFFF',
          'base-200': '#F8FAFC',
          'base-300': '#E2E8F0',
          'base-content': '#0A192F',
          info: '#3B82F6',
          'info-content': '#FFFFFF',
          success: '#22C55E',
          'success-content': '#FFFFFF',
          warning: '#F59E0B',
          'warning-content': '#FFFFFF',
          error: '#EF4444',
          'error-content': '#FFFFFF',
          '--rounded-box': '0.375rem',
          '--rounded-btn': '0.25rem',
          '--rounded-badge': '1.9rem',
          '--animation-btn': '0.25s',
          '--animation-input': '.2s',
          '--btn-focus-scale': '0.95',
          '--border-btn': '1px',
          '--tab-border': '1px',
          '--tab-radius': '0.375rem',
        },
      },
    ],
    darkTheme: false,
    base: true,
    styled: true,
    utils: true,
    logs: false,
  },
}
